#!/bin/bash

rostopic pub /srh/sendupdate sr_robot_msgs/sendupdate "{sendupdate_length: 20 ,sendupdate_list: [{joint_name: FFJ0,joint_target: 42.07},{joint_name: FFJ3,joint_target:  49},{joint_name: FFJ4 ,joint_target: -17.85},{joint_name:  LFJ0 ,joint_target: 2.57},{joint_name: LFJ3 ,joint_target: 2.93},{joint_name: LFJ4 ,joint_target: -24.88},{joint_name: LFJ5 ,joint_target: 0.26},{joint_name:  MFJ0 ,joint_target: 50.63},{joint_name: MFJ3 ,joint_target: 35.58},{joint_name: MFJ4, joint_target: 3.4},{joint_name: RFJ0 ,joint_target: 54.11},{joint_name:  RFJ3 ,joint_target: 39.26},{joint_name: RFJ4 ,joint_target: -24.9},{joint_name: THJ1 ,joint_target: 4.12},{joint_name:  THJ2 ,joint_target: 23.42},{joint_name:  THJ3 ,joint_target: 14.52},{joint_name: THJ4 ,joint_target: 70.35},{joint_name: THJ5 ,joint_target: 5.89},{joint_name: WRJ1 ,joint_target: 17.79},{joint_name:  WRJ2 ,joint_target: -3.28}]}"





  



 
 


 



 
 









