#!/bin/bash

rostopic pub /srh/sendupdate sr_robot_msgs/sendupdate "{sendupdate_length: 20 ,sendupdate_list: [{joint_name: FFJ0,joint_target: 57.45},{joint_name: FFJ3,joint_target:  42.30},{joint_name: FFJ4 ,joint_target: -24.59},{joint_name:  LFJ0 ,joint_target: 0.31},{joint_name: LFJ3 ,joint_target: 17.17},{joint_name: LFJ4 ,joint_target: -21.01},{joint_name: LFJ5 ,joint_target: 6.07},{joint_name:  MFJ0 ,joint_target: 35.63},{joint_name: MFJ3 ,joint_target: 47.76},{joint_name: MFJ4, joint_target: -3.02},{joint_name: RFJ0 ,joint_target: 53.50},{joint_name:  RFJ3 ,joint_target: 47.76},{joint_name: RFJ4 ,joint_target: -14.76},{joint_name: THJ1 ,joint_target: 3.62},{joint_name:  THJ2 ,joint_target: 18.21},{joint_name:  THJ3 ,joint_target: 3.08},{joint_name: THJ4 ,joint_target: 70.46},{joint_name: THJ5 ,joint_target: 5.89},{joint_name: WRJ1 ,joint_target: 17.79},{joint_name:  WRJ2 ,joint_target: -3.28}]}"





  



 
 


 



 
 









