#!/bin/bash

rostopic pub /srh/sendupdate sr_robot_msgs/sendupdate "{sendupdate_length: 20 ,sendupdate_list: [{joint_name: FFJ0,joint_target: 0},{joint_name: FFJ3,joint_target:  0},{joint_name: FFJ4 ,joint_target: 0},{joint_name:  LFJ0 ,joint_target: 0},{joint_name: LFJ3 ,joint_target: 0},{joint_name: LFJ4 ,joint_target: 0},{joint_name: LFJ5 ,joint_target: 0},{joint_name:  MFJ0 ,joint_target: 0},{joint_name: MFJ3 ,joint_target: 0},{joint_name: MFJ4, joint_target: 0},{joint_name: RFJ0 ,joint_target: 0},{joint_name:  RFJ3 ,joint_target: 0},{joint_name: RFJ4 ,joint_target: 0},{joint_name: THJ1 ,joint_target: 0},{joint_name:  THJ2 ,joint_target: 0},{joint_name:  THJ3 ,joint_target: 0},{joint_name: THJ4 ,joint_target: 0},{joint_name: THJ5 ,joint_target: 0},{joint_name: WRJ1 ,joint_target: 0},{joint_name:  WRJ2 ,joint_target: 0}]}"





  



 
 


 



 
 









